### PR TITLE
Avoid case-sensitive workspace names

### LINKED ISSUE #52: Colliding workspace names on case-insensitive system
Hazel generates an external workspace for each of the packages provided in the `core_packages` and `packages` attributes to `hazel_repositiories`. E.g. `haskell_vector` for `vector`. Hackage allows package names to only differ in case. E.g. `HSet` and `hset`. This will generate workspace names `haskell_HSet` and `haskell_hset`. On a case-insensitive system, in particular on Windows, Bazel will not distinguish these two workspace names, leading to errors like the following:

```
ERROR: C:/users/user/_bazel_user/glk6p2o5/external/ai_formation_hazel/hazel.bzl:172:3: Label '@haskell_HSet//:files' is duplicated in the 'files' attribute of rule 'all_hazel_packages'
```

## Temporary Workaround

Commenting out instances of such names in the generated `hazel/packages.bzl` file resolves that issue. (Of course that's just a work around)

## Proposed resolution

I've done some preliminary tests on Windows with the following approach and they show that it resolves this issue.

I propose to append case-sensitive information to the generated workspace names. To that end we can use the [`hash` function](https://docs.bazel.build/versions/master/skylark/lib/globals.html#hash) that Bazel offers, and append the hash of the package name to the generated workspace name. We can also lower case workspace names to ensure that other issues related to case insensitivity are also caught on Linux.

This would generate workspace names like the following
```
HSet -> haskell_hset_2227962
hset -> haskell_hset_3212026
SCalendar -> haskell_scalendar_191454385
scalendar -> haskell_scalendar__1877157711
```
(The double `_` occurs when the result of `hash` is a negative number)

Disadvantages:
- It makes it harder for users to predict the generated workspace names and query information about external dependencies. Maybe this can be resolved using `bazel query` or a package group.
- This assumes that there are no hash collisions between package names that only differ in case. (I haven't observed any so far) If collisions ever occur, the method could be further refined.

Let me know what you think of this approach and I'll be happy to create a PR.

### PR DESCRIPTION
**Pull request by aherrmann-da**
closes #52

- This changes modifies the way Hazel generates workspace names such that they become case-insensitive. This is done by appending a hash of the package name as proposed in #52.
- This change also unifies the Hazel name mangling into one extension file `tools/mangling.bzl` providing `hazel_workspace`, `hazel_library`, and `hazel_binary` functions in one location.

### CODE REVIEW

**Comment by judah** [comment]
I think it would be good to add more documentation in the README on how to discover what the hash is for a particular package.  (That would help when debugging a package directly with `blaze query` or `blaze build`.)

In theory, you should be able to get the list of packages already by running something like `blaze query "deps(@all_hazel_packages//:all-package-files,1)`.   However, it might make sense to generate more rules to make these steps easier for users.  Some possible ideas:  (1) For each package `haskell_foo`, generate a file in `all_hazel_packages` named `haskell_foo` which contains the full repository name like `haskell_foo_12345`.  (2) Create a rule like:

```
filegroup(
    name = "haskell_foo",
    deps = ["@haskell_foo_12345//:files],
)
```

So that `blaze query "deps(@all_hazel_repositories//:haskell_foo, 1)"` prints the repository name.

**Comment by thumphries** [comment]
The implementation here looks good. I've tested it with our fairly large internal repo, which involved updating a few direct repository references to include their hashes.

I'm still not quite sure we're doing the right thing, though it certainly solves the acute problem on case-insensitive filesystems. Are there any other rulesets that deal with the same problem? Or is Hackage the only package repository to allow case-equivalent packages :sweat_smile:

**Comment by aherrmann** [comment]
@thumphries 
> Are there any other rulesets that deal with the same problem? Or is Hackage the only package repository to allow case-equivalent packages sweat_smile

Very good question! For reference I had a look at Python, Java/Scala, and Golang, see below for details. Of what I could find it seems that this here is the first instance of this issue surfacing. It seems that most packaging ecosystems either don't allow package names to only differ in case, or have longer package coordinates including organization names that make such collisions unlikely.

---

Looking at rules_python they [use lower-cased versions of package names](https://github.com/bazelbuild/rules_python/pull/11/files), because apparently

> From PEP 508 it appears that you can register packages with any capitalization, and install them with any capitalization, even if it's different. I.e. you can register package 'MyPackage' and install it with mypackage, MYPACKAGE, or even mYpAcKaGe.

In the JVM world, Maven coordinates are case-sensitive, in the sense that if you specify `Guava` as a dependency then Maven won't find `guava`. But, it seems that the Maven repository [doesn't allow to create packages with names that only differ in case](https://issues.sonatype.org/browse/NEXUS-8764?jql=text%20~%20%22case%20sensitive%22).

> The repository.name is case-sensitive, but due to its direct use in elasticsearch (which is not case-sensitive) validation for repository creation will prevent you from creating another repository with a name with difference in only case.

So, this seems to be a non-issue for any of the JVM rules. If, perhaps, only incidentally.

In rules_go I couldn't find any handling of upper case in package names. I'm no Go expert, but my understanding is that third-party packages are always fully qualified, including some sort of organization/author identifier. This makes such upper/lower case collisions very unlikely. I could only find [one instance](https://github.com/bazelbuild/rules_go/issues/1064) where an organization renamed itself to an all lower case spelling. In that case rules_go decided not to act.

**Comment by aherrmann-da** [comment]
@thumphries I noticed that I made a silly mistake in the `hazel_custom_package_*` rules, sorry about that! I've fixed it in the latest commit. Maybe that was related to the subtle build failures that you encountered?

**Comment by thumphries** [comment]
Actually, I suspect we were broken by the change in https://github.com/tweag/rules_haskell/pull/550

Let's just merge this (since it is working for you) and I'll revisit once we catch up to rules_haskell master.

Again, sorry for the slow.

**Comment by mjrussell** [comment]
One thing to note about this change is that it breaks the current workaround TH embedFile with extra_src. The path done [here](https://github.com/FormationAI/wai/commit/aaa0dca56231c060372004cda46d719ec6cc3ec5) is now mangled.

I mentioned it in #57, but Im hoping a similar sym link approach might work

**Pull request merged**
